# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: node_js
      node_js: 14
      python: "3.8"
      install:
        - source ~/virtualenv/python3.8/bin/activate
        - yarn install --frozen-lockfile
        - pip install coveralls
        - yarn global add coveralls
        - gem install coveralls-lcov
      script:
        - cd frontend/probloom
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - cd ../../backend/probloom
        - pip install -r requirements.txt
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - sonar-scanner
        - coveralls --merge=../../frontend/probloom/coverage.json
